/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qiujuer_ndkdemo_jni_StringKit */

#ifndef _Included_net_qiujuer_ndkdemo_jni_StringKit
#define _Included_net_qiujuer_ndkdemo_jni_StringKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qiujuer_ndkdemo_jni_StringKit
 * Method:    setNull
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_qiujuer_ndkdemo_jni_StringKit_setNull
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
